api_advertisement:
    resource: HouseFinder\APIBundle\Controller\AdvertisementController
    type:     annotation
    defaults: {_format: json}
    prefix:   /api/advertisement/

api_address:
    resource: HouseFinder\APIBundle\Controller\AddressController
    type:     annotation
    defaults: {_format: json}
    prefix:   /api/address/