parameters:
#    house_finder_api.example.class: HouseFinder\APIBundle\Example

services:
#    house_finder_api.example:
#        class: %house_finder_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
