language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - cp app/config/parameters.yml.test app/config/parameters.yml
  - composer install -n --prefer-source
  - mysql -e 'create database housefinder;'
  - php app/console doctrine:schema:update --force

script: phpunit -c app
